### ISSUE TITLE
release 0.20.0

### ISSUE THREAD

**Issue by michaeldwan** [firecracker-microvm/firecracker-go-sdk#172]
Looks like 0.20.0 is mentioned in the changelog but hasn't been tagged yet -- is it ready for a release?

**Comment by kzys** [comment]
Yes. We will tag the release pretty soon!

**Comment by kzys** [comment]
We've just realized that SDK is currently not compatible with Firecracker's Vsock protocol change (https://github.com/firecracker-microvm/firecracker/commit/a271d08f0b1ba0ee82761cd49244b6a8017bcede#diff-1b131960ac0b33a6de812a32a990a882).

**Comment by jeromegn** [comment]
We've been having some trouble with reconnecting to a vsock, but only sometimes. This is a weird one, not sure if related. I can't replicate locally, this is only happening in our production setup afaict.

**Comment by kzys** [comment]
Thanks for reporting @jeromegn! Can you open an issue with the details of the problem? It may not be related, since the vsock change would break us 100%.

Regarding the vsock change, apparently we don't have to fix the SDK since vsock handling is mostly in firecracker-containerd side, but we have found that Firecracker 0.20.0 has another backward-incompatible change (https://github.com/firecracker-microvm/firecracker/pull/1547).

**Comment by luxas** [comment]
Friendly ping on tagging the v0.20.0 release, for easier vendoring :)
Thanks for all your work!

**Comment by kzys** [comment]
We have released 0.20.0 finally! Regarding the backward incompatible change, it only affects errors and the fix has been merged into firecracker/master already.

https://github.com/firecracker-microvm/firecracker-go-sdk/releases/tag/v0.20.0
