### ISSUE TITLE
publishing `tc-redirect-tap` in releases

### ISSUE THREAD

**Issue by smira** [firecracker-microvm/firecracker-go-sdk#174]
Could you please publish `tc-redirect-tap` on Releases for the next release, so that users can easily download it when setting up something using Firecracker and CNI.

**Comment by kzys** [comment]
We may separate this command from the Go SDK, since

- `tc-redirect-tap` is not really tied to Firecracker. There may be other use cases.
- The command is relatively stable than the SDK itself.
- The SDK doesn't have binary releases. Our "release" is simply a Git tag.

Let us know if it doesn't work for you!

**Comment by smira** [comment]
yes, any kind of binary release will be just perfect, if it's on separate repo that might be even easier.

**Comment by kzys** [comment]
Thanks @smira. I'm going to create awslabs/tc-redirect-tap to host the plugin.

**Comment by mazzy89** [comment]
Where can I get `tc-redirect-tap`? I haven't found under awslabs/tc-redirect-tap.

**Comment by kzys** [comment]
Sorry. We are still in the process of creating the repository.

**Comment by mazzy89** [comment]
Sure. No problems. Thanks for reacting on this fast. If I may help anyhow, just ping me.

**Comment by kzys** [comment]
We've open-sourced https://github.com/awslabs/tc-redirect-tap. We are going to prepare binary releases on the repository.

**Comment by kzys** [comment]
Resolving. We are going to track the binary releases in https://github.com/awslabs/tc-redirect-tap/issues/6.
